export const rules = {
    "init-declarations": "off",
    "no-catch-shadow": "off",
    "no-delete-var": "error",
    "no-label-var": "error",
    "no-shadow-restricted-names": "error",
    "no-undef": "error",
    "no-undef-init": "error",
    "no-undefined": "off",
    camelcase: [
        "error",
        {
            properties: "never",
            ignoreDestructuring: false,
        },
    ],
    "capitalized-comments": [
        "off",
        "never",
        {
            line: {
                ignorePattern: ".*",
                ignoreInlineComments: true,
                ignoreConsecutiveComments: true,
            },
            block: {
                ignorePattern: ".*",
                ignoreInlineComments: true,
                ignoreConsecutiveComments: true,
            },
        },
    ],
    "consistent-this": "off",
    "func-name-matching": [
        "off",
        "always",
        {
            includeCommonJSModuleExports: false,
            considerPropertyDescriptor: true,
        },
    ],
    "func-style": [
        "off",
        "expression",
    ],
    "id-denylist": "off",
    "id-length": "off",
    "id-match": "off",
    "lines-around-directive": [
        "error",
        {
            before: "always",
            after: "always",
        },
    ],
    "max-depth": [
        "off",
        4,
    ],
    "max-lines": [
        "off",
        {
            max: 300,
            skipBlankLines: true,
            skipComments: true,
        },
    ],
    "max-lines-per-function": [
        "off",
        {
            max: 50,
            skipBlankLines: true,
            skipComments: true,
            IIFEs: true,
        },
    ],
    "max-nested-callbacks": "off",
    "max-params": [
        "off",
        3,
    ],
    "max-statements": [
        "off",
        10,
    ],
    "newline-after-var": "off",
    "newline-before-return": "off",
    "no-array-constructor": "error",
    "no-inline-comments": "off",
    "no-lonely-if": "error",
    "no-negated-condition": "off",
    "no-new-object": "error",
    "no-spaced-func": "error",
    "no-ternary": "off",
    "no-unneeded-ternary": [
        "error",
        {
            defaultAssignment: false,
        },
    ],
    "one-var": [
        "error",
        "never",
    ],
    "operator-assignment": [
        "error",
        "always",
    ],
    "prefer-exponentiation-operator": "error",
    "prefer-object-spread": "error",
    "require-jsdoc": "off",
    "sort-keys": [
        "off",
        "asc",
        {
            caseSensitive: false,
            natural: true,
        },
    ],
    "sort-vars": "off",
    "unicode-bom": [
        "error",
        "never",
    ],
    "callback-return": "off",
    "handle-callback-err": "off",
    "no-buffer-constructor": "error",
    "no-mixed-requires": [
        "off",
        false,
    ],
    "no-new-require": "error",
    "no-path-concat": "error",
    "no-process-env": "off",
    "no-process-exit": "off",
    "no-restricted-modules": "off",
    "no-sync": "off",
    "arrow-body-style": [
        "error",
        "as-needed",
        {
            requireReturnForObjectLiteral: false,
        },
    ],
    "no-class-assign": "error",
    "no-const-assign": "error",
    "no-dupe-class-members": "error",
    "no-duplicate-imports": "off",
    "no-new-symbol": "error",
    "no-restricted-exports": [
        "error",
        {
            restrictedNamedExports: [
                "default",
                "then",
            ],
        },
    ],
    "no-this-before-super": "error",
    "no-useless-computed-key": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": [
        "error",
        {
            ignoreDestructuring: false,
            ignoreImport: false,
            ignoreExport: false,
        },
    ],
    "no-var": "error",
    "object-shorthand": [
        "error",
        "always",
        {
            ignoreConstructors: false,
            avoidQuotes: true,
        },
    ],
    "prefer-const": [
        "error",
        {
            destructuring: "any",
            ignoreReadBeforeAssign: true,
        },
    ],
    "prefer-numeric-literals": "error",
    "prefer-reflect": "off",
    "prefer-spread": "error",
    "require-yield": "error",
    "sort-imports": [
        "off",
        {
            ignoreCase: false,
            ignoreDeclarationSort: false,
            ignoreMemberSort: false,
            memberSyntaxSortOrder: [
                "none",
                "all",
                "multiple",
                "single",
            ],
        },
    ],
    "symbol-description": "error",
    "for-direction": "error",
    "getter-return": [
        "error",
        {
            allowImplicit: true,
        },
    ],
    "no-async-promise-executor": "error",
    "no-await-in-loop": "error",
    "no-cond-assign": [
        "error",
        "always",
    ],
    "no-constant-condition": "warn",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-dupe-args": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-func-assign": "error",
    "no-import-assign": "error",
    "no-inner-declarations": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-misleading-character-class": "error",
    "no-obj-calls": "error",
    "no-regex-spaces": "error",
    "no-setter-return": "error",
    "no-sparse-arrays": "error",
    "no-template-curly-in-string": "error",
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unreachable-loop": [
        "error",
        {
            ignore: [],
        },
    ],
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unused-private-class-members": "off",
    "no-useless-backreference": "error",
    "no-negated-in-lhs": "off",
    "require-atomic-updates": "off",
    "use-isnan": "error",
    "valid-jsdoc": "off",
    "valid-typeof": [
        "error",
        {
            requireStringLiterals: true,
        },
    ],
    "accessor-pairs": "off",
    "array-callback-return": [
        "error",
        {
            allowImplicit: true,
        },
    ],
    "block-scoped-var": "error",
    complexity: [
        "off",
        20,
    ],
    curly: [
        "error",
        "multi-line",
    ],
    "default-case": [
        "error",
        {
            commentPattern: "^no default$",
        },
    ],
    "default-case-last": "error",
    "dot-notation": [
        "error",
        {
            allowKeywords: true,
        },
    ],
    "grouped-accessor-pairs": "error",
    "no-alert": "warn",
    "no-caller": "error",
    "no-case-declarations": "error",
    "no-constructor-return": "error",
    "no-div-regex": "off",
    "no-else-return": [
        "error",
        {
            allowElseIf: false,
        },
    ],
    "no-empty-function": [
        "error",
        {
            allow: [
                "arrowFunctions",
                "functions",
                "methods",
            ],
        },
    ],
    "no-empty-pattern": "error",
    "no-eq-null": "off",
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-extra-label": "error",
    "no-fallthrough": "error",
    "no-global-assign": [
        "error",
        {
            exceptions: [],
        },
    ],
    "no-native-reassign": "off",
    "no-implicit-coercion": [
        "off",
        {
            boolean: false,
            number: true,
            string: true,
            allow: [],
        },
    ],
    "no-implicit-globals": "off",
    "no-implied-eval": "error",
    "no-invalid-this": "off",
    "no-iterator": "error",
    "no-labels": [
        "error",
        {
            allowLoop: false,
            allowSwitch: false,
        },
    ],
    "no-lone-blocks": "error",
    "no-loop-func": "error",
    "no-magic-numbers": [
        "off",
        {
            ignore: [],
            ignoreArrayIndexes: true,
            enforceConst: true,
            detectObjects: false,
        },
    ],
    "no-multi-str": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-octal": "error",
    "no-octal-escape": "error",
    "no-proto": "error",
    "no-redeclare": "error",
    "no-restricted-properties": [
        "error",
        {
            object: "arguments",
            property: "callee",
            message: "arguments.callee is deprecated",
        },
        {
            object: "global",
            property: "isFinite",
            message: "Please use Number.isFinite instead",
        },
        {
            object: "self",
            property: "isFinite",
            message: "Please use Number.isFinite instead",
        },
        {
            object: "window",
            property: "isFinite",
            message: "Please use Number.isFinite instead",
        },
        {
            object: "global",
            property: "isNaN",
            message: "Please use Number.isNaN instead",
        },
        {
            object: "self",
            property: "isNaN",
            message: "Please use Number.isNaN instead",
        },
        {
            object: "window",
            property: "isNaN",
            message: "Please use Number.isNaN instead",
        },
        {
            property: "__defineGetter__",
            message: "Please use Object.defineProperty instead.",
        },
        {
            property: "__defineSetter__",
            message: "Please use Object.defineProperty instead.",
        },
        {
            object: "Math",
            property: "pow",
            message: "Use the exponentiation operator (**) instead.",
        },
    ],
    "no-return-await": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-throw-literal": "error",
    "no-unmodified-loop-condition": "off",
    "no-unused-expressions": [
        "error",
        {
            allowShortCircuit: false,
            allowTernary: false,
            allowTaggedTemplates: false,
        },
    ],
    "no-unused-labels": "error",
    "no-useless-call": "off",
    "no-useless-catch": "error",
    "no-useless-concat": "error",
    "no-useless-escape": "error",
    "no-useless-return": "error",
    "no-void": "error",
    "no-warning-comments": [
        "off",
        {
            terms: [
                "todo",
                "fixme",
                "xxx",
            ],
            location: "start",
        },
    ],
    "no-with": "error",
    "prefer-promise-reject-errors": [
        "error",
        {
            allowEmptyReject: true,
        },
    ],
    "prefer-named-capture-group": "off",
    radix: "error",
    "require-await": "off",
    "require-unicode-regexp": "off",
    "vars-on-top": "error",
    yoda: "error",
};
